### ISSUE TITLE
Add writable Pipe

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/TangoTest#6]
subj

**Comment by mliszcz** [comment]
Hi @Ingvord
We'd like to work work on this issue. Do you have any specific requirements what data structure should  be stored inside the pipe? We could make it simple (e.g. just three data elements, like int+double+string) or more complex (e.g. structure would be dynamically configured via device property).

Also @bourtemb do you have any comments on this?

CC @katrze89

**Comment by mliszcz** [comment]
CC @piogor

**Comment by bourtemb** [comment]
A pipe is a dynamic data structure, so in theory the data structure can change at any call.
Usually, the client knows what data structure the device server is expecting but it could be completely generic and dynamic too.
I think It might be interesting to have something generic which accepts any data structure and provides a way to re-read what was lastly written.

**Comment by mliszcz** [comment]
Thanks @bourtemb. In this case, we will copy the blob upon write and during read we will either return what was recently written or return an empty blob (if read is before write).
